/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_utils_Encryptor */

#ifndef _Included_com_android_utils_Encryptor
#define _Included_com_android_utils_Encryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_utils_Encryptor
 * Method:    desDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_utils_Encryptor_desDecrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_utils_Encryptor
 * Method:    desEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_utils_Encryptor_desEncrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_android_utils_Encryptor
 * Method:    aesCrypt
 * Signature: ([BJI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_android_utils_Encryptor_aesCrypt
  (JNIEnv *, jobject, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
